[package]
name = "geo_plegmata"
version = "0.2.0"
license = "MIT"
edition = "2024"
readme = "README.md"

[dependencies]
geo = "0.29.3"
rand = "0.8.5"
tracing = "0.1.41"

[dev-dependencies]

[lib]
name = "geo_plegmata"
path = "src/lib.rs"
